### ISSUE TITLE
[feature request] Adding padding for the items(BubbleBottomBarItem)

### ISSUE THREAD

**Issue by iampato** [westdabestdb/bubble_bottom_bar#24]

**Comment by gabrielhn** [comment]
I vote that too. Padding top and bottom.

**Comment by ciriousjoker** [comment]
I need padding left and right. I can't use it as a floating rounded bar, because the padding doesn't match:

![Screenshot_20200905-074821](https://user-images.githubusercontent.com/16866223/92298759-64728080-ef4c-11ea-813f-9c160ba14570.png)

**Comment by luis-cruzt** [comment]
@westdabestdb any update on this feature request?

**Comment by iampato** [comment]
if you need this urgently you can always do this in your `pubspec.yaml` 
```
dependencies:
  flutter:
    sdk: flutter
  bubble_bottom_bar:
    git:
      url: https://github.com/Iampato/bubble_bottom_bar.git
      ref: 3135f5a84d79c399edef21a39c8eaebc7cecdfb2
```
